# Latitude (WGS-84).
float64 lat
# Longitude (WGS-84).
float64 lon
# Height (WGS-84).
float32 height
# Offset north.
float32 x
# Offset east.
float32 y
# Offset down.
float32 z
# Rotation over x axis.
float32 phi
# Rotation over y axis.
float32 theta
# Rotation over z axis.
float32 psi
# Body-Fixed xx Velocity.
float32 u
# Body-Fixed yy Velocity.
float32 v
# Body-Fixed zz Velocity.
float32 w
# Ground Velocity X (North).
float32 vx
# Ground Velocity Y (East).
float32 vy
# Ground Velocity Z (Down).
float32 vz
# Angular Velocity in x.
float32 p
# Angular Velocity in y.
float32 q
# Angular Velocity in z.
float32 r
# Depth.
float32 depth
# Altitude.
float32 alt